
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IS = 4;
  public static final int LT = 9;
  public static final int L_BRA = 2;
  public static final int SEMI = 6;
  public static final int REL = 18;
  public static final int GT = 8;
  public static final int SET_OPERATOR = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int GT_EQ = 10;
  public static final int error = 1;
  public static final int LT_EQ = 11;
  public static final int EQ = 12;
  public static final int REL_DEFINITION = 7;
  public static final int R_BRA = 3;
  public static final int SET_VAR = 17;
  public static final int SET_DELI = 5;
  public static final int VAR = 16;
  public static final int NOT_EQ = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "L_BRA",
  "R_BRA",
  "IS",
  "SET_DELI",
  "SEMI",
  "REL_DEFINITION",
  "GT",
  "LT",
  "GT_EQ",
  "LT_EQ",
  "EQ",
  "NOT_EQ",
  "SET_OPERATOR",
  "NUMBER",
  "VAR",
  "SET_VAR",
  "REL"
  };
}

