
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_BRA = 5;
  public static final int NUMBER = 13;
  public static final int SET = 12;
  public static final int SEMI = 8;
  public static final int EOF = 0;
  public static final int VAR = 14;
  public static final int REL = 11;
  public static final int SET_OPERATORS = 10;
  public static final int L_BRA = 4;
  public static final int SET_VAR = 15;
  public static final int REL_DEFINITION = 9;
  public static final int GT = 2;
  public static final int error = 1;
  public static final int SET_DELI = 7;
  public static final int LT = 3;
  public static final int IS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GT",
  "LT",
  "L_BRA",
  "R_BRA",
  "IS",
  "SET_DELI",
  "SEMI",
  "REL_DEFINITION",
  "SET_OPERATORS",
  "REL",
  "SET",
  "NUMBER",
  "VAR",
  "SET_VAR"
  };
}

