
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_BRA = 5;
  public static final int NUMBER = 9;
  public static final int EOF = 0;
  public static final int VAR = 8;
  public static final int REL = 7;
  public static final int L_BRA = 4;
  public static final int GT = 2;
  public static final int error = 1;
  public static final int LT = 3;
  public static final int IS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GT",
  "LT",
  "L_BRA",
  "R_BRA",
  "IS",
  "REL",
  "VAR",
  "NUMBER"
  };
}

